import {
  Activity,
  Apple,
  Atom,
  Baby,
  BatteryCharging,
  Bean,
  Beef,
  BicepsFlexed,
  Bike,
  Bone,
  Brain,
  Candy,
  Carrot,
  Citrus,
  Coffee,
  Cookie,
  CupSoda,
  Droplet,
  Droplets,
  Dumbbell,
  Egg,
  Eye,
  Fish,
  FlaskConical,
  Flame,
  Flower2,
  Footprints,
  Gift,
  GlassWater,
  Heart,
  HeartPulse,
  Leaf,
  Milk,
  Moon,
  Nut,
  Package,
  Percent,
  Pill,
  PillBottle,
  Salad,
  Scale,
  Shield,
  ShieldPlus,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Tablets,
  Tag,
  Target,
  Timer,
  Trophy,
  VenusAndMars,
  Wheat,
  Zap,
  type LucideIcon,
} from "lucide-react";

// Icons of category and goal tiles (lucide names: the built-in taxonomy's icons + CATEGORY_ICONS the admin can pick).
// A static map instead of lucide's dynamic loader: no extra requests and no flash of an empty tile.
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  atom: Atom,
  baby: Baby,
  "battery-charging": BatteryCharging,
  bean: Bean,
  beef: Beef,
  "biceps-flexed": BicepsFlexed,
  bike: Bike,
  bone: Bone,
  brain: Brain,
  candy: Candy,
  carrot: Carrot,
  citrus: Citrus,
  coffee: Coffee,
  cookie: Cookie,
  "cup-soda": CupSoda,
  droplet: Droplet,
  droplets: Droplets,
  dumbbell: Dumbbell,
  egg: Egg,
  eye: Eye,
  fish: Fish,
  "flask-conical": FlaskConical,
  flame: Flame,
  "flower-2": Flower2,
  footprints: Footprints,
  gift: Gift,
  "glass-water": GlassWater,
  heart: Heart,
  "heart-pulse": HeartPulse,
  leaf: Leaf,
  milk: Milk,
  moon: Moon,
  nut: Nut,
  package: Package,
  percent: Percent,
  pill: Pill,
  "pill-bottle": PillBottle,
  salad: Salad,
  scale: Scale,
  shield: Shield,
  "shield-plus": ShieldPlus,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  tablets: Tablets,
  tag: Tag,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  "venus-and-mars": VenusAndMars,
  wheat: Wheat,
  zap: Zap,
};

/** Decorative icon of a category / goal (falls back to a capsule for unknown names). No hooks: usable anywhere. */
export function CategoryIcon({ icon, className, strokeWidth = 1.75 }: { icon: string; className?: string; strokeWidth?: number }) {
  const Icon = ICONS[icon] ?? Pill;
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden />;
}
